#!/bin/bash
#
# ThemeMaster
# https://github.com/JohnIrvine1433/ThemeMaster
# Description : dependencies management module
#

if id "ark" &>/dev/null || id "odroid" &>/dev/null; then
  if ! dpkg -s "dialog" &> /dev/null ; then
    install_dependencies="dialog"
  fi

  if ! dpkg -s "unzip" &> /dev/null ; then
    install_dependencies="$install_dependencies unzip"
  fi

  if ! dpkg -s "wget" &> /dev/null ; then
    install_dependencies="$install_dependencies wget"
  fi

  if ! dpkg -s "libevdev2" &> /dev/null ; then
    install_dependencies="$install_dependencies libevdev2"
  fi

  if [ ! -z "$install_dependencies" ]
  then
    printf "\e[32mInstalling dependencies ...\n" > /dev/tty1
    sudo apt update && sudo apt install -y $install_dependencies --no-install-recommends
  fi
fi
