#!/bin/bash
#
# ThemeMaster
# https://github.com/JohnIrvine1433/ThemeMaster
# Description : post installation module, loaded after having downloaded the new version
#

function PostInstallUpdater() {
  local changes
  local temp
  local nbchanges

  dialog --clear
  dialog --infobox "Processing post-installation ..." 5 50 >/dev/tty1

####################################
# FORWARD COMPATIBLE MODIFICATIONS #
####################################
#
#Removing deprecated files
#
  #from v3.0.0
  rm -f gamecontrollerdb.txt
  #from v3.2.0
  rm -f ./oga_controls
  rm -f ./anbernic_controls
  #from v4.0.0
  rm -f ./helper
#
# Renaming files
#
  #from v3.0.0
  mkdir -p ./data/
  for file in *.log; do
    mv -- "$file" "./data/${file%.log}.version"
  done
#
# ThemeMaster configuration file changes
#
  #from v3.0.1
  #app_location is now dynamic, remove it from config file
  #from v3.1.0
  #add debug mode, add variable to config file
  #From v4.0.0
  #user can now choose to use prerelease versions
  #change debug variable from 1/0 to on/off
  echo "app_conf_version=\"4.0.0\"" >ThemeMaster.cfg
  echo "app_prerelease=\"off\"" >>ThemeMaster.cfg
  echo "debug=\"off\"" >>ThemeMaster.cfg
  echo "mode=\"${mode}\"" >>ThemeMaster.cfg
  echo "themes_location=\"${themes_location}\"" >>ThemeMaster.cfg
  echo "temp_ram_folder=\"${temp_ram_folder}\"" >>ThemeMaster.cfg
  echo "app_autocheckupdate=\"${app_autocheckupdate}\"" >>ThemeMaster.cfg
  echo "themes_autocheckupdate=\"${themes_autocheckupdate}\"" >>ThemeMaster.cfg
  echo "active_collection=\"${active_collection}\"" >>ThemeMaster.cfg
  echo "collections=(${collections[@]})" >>ThemeMaster.cfg
  echo "app_colorscheme=\"${app_colorscheme}\"" >>ThemeMaster.cfg

##########################
# ONE SHOT MODIFICATIONS #
##########################
#3.1.0 and 4.0.0
  #Fix cached_outdatedthemes, file reset
  rm -f ./data/outdatedthemes.cache

#Display changelog
  temp=$(grep -n "^v" ./changelog | head -2 | tail -1)
  nbchanges=${temp:0:1}
  nbchanges=$((nbchanges-1))
  changes=$(head -n $nbchanges changelog)
  dialog --clear --backtitle "ThemeMaster - System" --title "What's new is this new release?" --msgbox "$changes" 10 50 2>&1 >/dev/tty1
}
