#!/bin/bash
#
# ThemeMaster
# https://github.com/JohnIrvine1433/ThemeMaster
# Description : post installation module, loaded after having downloaded the new version
#

function PostInstallUpdater() {
  local changes
  local temp
  local nbchanges
  local temp_array1
  local temp_array2
  local updater_tty
  local updater_2_version="4.3.0"
  local ASSET_URL="https://github.com/${github_app_owner}/${github_app_repo}/releases/download/${updater_2_version}/ThemeMaster.nfo.zip"

  #ttyoutput global variable added from 4.3.0
  if [[ -z "$ttyoutput" ]]; then
    updater_tty="/dev/tty1"
  else
    updater_tty=$ttyoutput
  fi

  dialog --clear
  dialog --infobox "Processing post-installation ..." 5 50 >$updater_tty

####################################
# FORWARD COMPATIBLE MODIFICATIONS #
####################################
#
#Removing deprecated files
#
  #from v3.0.0
  rm -f gamecontrollerdb.txt
  #from v3.2.0
  rm -f ./oga_controls
  rm -f ./anbernic_controls
  #from v4.0.0
  rm -f ./helper
  #from v4.1.0
  rm -f ./controls
#
# Renaming files
#
  #from v3.0.0
  mkdir -p ./data/
  if [ $current_app_version \< "3.0.0" ]; then
    for file in *.log; do
      mv -- "$file" "./data/${file%.log}.version"
    done
  fi
#
# ThemeMaster configuration file changes
#
  #from v3.0.1
  #app_location is now dynamic, remove it from config file
  #from v3.1.0
  #add debug mode, add variable to config file
  #From v4.0.0
  #user can now choose to use prerelease versions
  #change debug variable from 1/0 to on/off
  #From v4.0.2
  #add farfenkugell to the GitHub repository list
  #From 4.1.0
  #do not overwrite manually added collections
  #From 4.2.0
  #Add gallery_user_res (Theme Gammery mode now relies on device's resolution)
  #From 4.3.0
  #Add variable to manage tty output
  admin_collections=("Jetup13" "CodyV59" "farfenkugell" "EmuELEC" "RetroPie")
  user_collections=($(comm -13 <(printf '%s\n' "${admin_collections[@]}" | LC_COLLATE=C sort -f) <(printf '%s\n' "${collections[@]}" | LC_COLLATE=C sort -f)))
  new_collections=("${admin_collections[@]}" "${user_collections[@]}")

  echo "app_conf_version=\"4.3.0\"" >ThemeMaster.cfg
  echo "app_prerelease=\"${app_prerelease}\"" >>ThemeMaster.cfg
  echo "debug=\"${debug}\"" >>ThemeMaster.cfg
  echo "mode=\"${mode}\"" >>ThemeMaster.cfg
  echo "themes_location=\"${themes_location}\"" >>ThemeMaster.cfg
  echo "temp_ram_folder=\"${temp_ram_folder}\"" >>ThemeMaster.cfg
  echo "app_autocheckupdate=\"${app_autocheckupdate}\"" >>ThemeMaster.cfg
  echo "themes_autocheckupdate=\"${themes_autocheckupdate}\"" >>ThemeMaster.cfg
  echo "active_collection=\"${active_collection}\"" >>ThemeMaster.cfg
  echo "collections=(${new_collections[@]})" >>ThemeMaster.cfg
  echo "app_colorscheme=\"${app_colorscheme}\"" >>ThemeMaster.cfg
  echo "gallery_user_res=\"${gallery_user_res}\"" >>ThemeMaster.cfg
  if [[ -z "$ttyoutput" ]]; then
    echo "ttyoutput=\"\"" >>ThemeMaster.cfg
  else
    echo "ttyoutput=\"${ttyoutput}\"" >>ThemeMaster.cfg
  fi

##########################
# ONE SHOT MODIFICATIONS #
##########################
#3.1.0 and 4.0.0
  #Fix cached_outdatedthemes, file reset
  if [ $current_app_version \< "4.0.0" ]; then
    rm -f ./data/outdatedthemes.cache
  fi

#4.2.0
  #Update ThemeGallery sourcing, files reset
  if [ $current_app_version \< "4.2.0" ]; then
    rm -f ./data/gallery.db
    rm -f ./data/gallery.version
  fi


################
# POST INSTALL #
################

if [ -e "ThemeMaster.nfo" ]; then
  #Downloading logo asset only to count down installations
  wget -a /tmp/ThemeMaster_wget.log -O - "$ASSET_URL" > /dev/null
else
  #Downloading and install logo asset
  wget -a /tmp/ThemeMaster_wget.log "$ASSET_URL" -O ${temp_ram_folder}app_update_temp/asset.zip
  #Unzipping archives
  unzip -qo ${temp_ram_folder}app_update_temp/asset.zip -d ${temp_ram_folder}app_update_temp/ #unzip directly in RAM
  #Copying logo file
  cp -f ${temp_ram_folder}app_update_temp/ThemeMaster.nfo $app_location/ThemeMaster/
fi

#Display changelog
  temp=$(grep -n "^v" ./changelog | head -2 | tail -1)
  nbchanges=${temp%:*}
  nbchanges=$((nbchanges-1))
  changes=$(head -n $nbchanges changelog)
  dialog --clear --backtitle "ThemeMaster - System" --title "What's new is this new release?" --msgbox "$changes" 10 50 2>&1 >$updater_tty
}
