#!/bin/bash
#
# ThemeMaster
# https://github.com/JohnIrvine1433/ThemeMaster
# Description : post installation module
#

function PostInstallUpdater() {

  dialog --clear
  dialog --infobox "Processing post-installation ..." 5 50 >/dev/tty1

  #v2.2.0 - creation of the post-installation updater
  #v3.0.0
  #gamecontrollerdb non longer used with bespoke controls files
  rm -f gamecontrollerdb.txt
  #Rename existing theme's installation log file extension from .log to .version
  mkdir -p ./data/
  for file in *.log; do
    mv -- "$file" "./data/${file%.log}.version"
  done
  #v3.0.1
  #app_location is now dynamic, remove it from config file
  echo "app_conf_version=\"${current_app_version}\"" >ThemeMaster.cfg
  echo "mode=\"${mode}\"" >>ThemeMaster.cfg
  echo "themes_location=\"${themes_location}\"" >>ThemeMaster.cfg
  echo "temp_ram_folder=\"${temp_ram_folder}\"" >>ThemeMaster.cfg
  echo "app_autocheckupdate=\"${app_autocheckupdate}\"" >>ThemeMaster.cfg
  echo "themes_autocheckupdate=\"${themes_autocheckupdate}\"" >>ThemeMaster.cfg
  echo "active_collection=\"${active_collection}\"" >>ThemeMaster.cfg
  echo "collections=(${collections[@]})" >>ThemeMaster.cfg
  echo "app_colorscheme=\"${app_colorscheme}\"" >>ThemeMaster.cfg

}
